name: Test Coverage Comment
on: pull_request
    
jobs:
  coverage_comment:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Test
        run: npx jest --coverage --coverageReporters json-summary

      - name: Type Coverage
        run: npm run type-coverage > type-coverage.txt

      - name: Type Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./type-coverage.txt

      - name: Test Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          titie: Test Coverage Report
          badge-title: coverage
